name: Publish Docker image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: "版本号 (例如: v1.0.0)"
        required: true
        default: "latest"
        type: string

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/webcloner_site

      # 手动触发时使用用户输入的版本号
      - name: Build and push (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true 
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/webcloner_site:${{ inputs.version }} 

      # 非手动触发时使用 metadata 生成的标签
      - name: Build and push (auto)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
